version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: ups_bank
      POSTGRES_USER: felipep
      POSTGRES_PASSWORD: mariapaz28
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql

  backend-upsbank:
    build: ./backend-upsbank
    container_name: backend-upsbank
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ups_bank
      SPRING_DATASOURCE_USERNAME: felipep
      SPRING_DATASOURCE_PASSWORD: mariapaz28
    depends_on:
      - db

  frontend-upsbank:
    build: ./frontend-upsbank
    container_name: frontend-upsbank
    ports:
      - "4200:80"
    depends_on:
      - backend-upsbank

volumes:
  postgres-data:

