apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-upsbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: felipe2p05/backend-upsbank:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/ups_bank"
            - name: SPRING_DATASOURCE_USERNAME
              value: "felipep"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mariapaz28"
