apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-upsbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: felipe2p05/frontend-upsbank:latest
          ports:
            - containerPort: 80
